DROP TABLE IF EXISTS BOX;

CREATE TABLE BOX (
       ID INT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(255) NOT NULL
     , FORMAT VARCHAR(255) NOT NULL
     , FILE LONGBLOB NOT NULL
     , SIZE INT NOT NULL
     , UNIQUE UQ_BOX (NAME, FORMAT)
     , PRIMARY KEY (ID)
);

